apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-job
spec:
  type: Scala
  mode: cluster
  image: "localhost:5000/spark-job:16"
  imagePullPolicy: Always
  imagePullSecrets:
    - docker.na1.hsdp.io
  mainClass: stackoverflow.StackOverflow
  mainApplicationFile: "local:///opt/spark/kursova-spark-hbase_2.12-0.1.0-SNAPSHOT.jar"
  sparkVersion: "2.4.4"
  restartPolicy:
    type: Never
  volumes:
    - name: hadoop-config-volume
      configMap:
        name: pinc-hbase
    - name: hbase-config-volume
      configMap:
        name: hbase-configmap
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 2.4.4
    serviceAccount: stas-sparkoperator
    volumeMounts:
      - name: "hadoop-config-volume"
        mountPath: "/etc/hadoop/conf/"
      - name: "hbase-config-volume"
        mountPath: "/etc/hbase/conf/"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.4
    volumeMounts:
      - name: "hadoop-config-volume"
        mountPath: "/etc/hadoop/conf/"
      - name: "hbase-config-volume"
        mountPath: "/etc/hbase/conf/"
